### ISSUE TITLE
how to fix this?

### ISSUE THREAD

**Issue by AimerEGOIST** [Aoi-hosizora/manhuagui_flutter#16]
![Screenshot_2021-06-11-23-42-10-509_com aoihosizora manhuagui](https://user-images.githubusercontent.com/48597571/121714476-6f2bf880-cb10-11eb-9332-da645f605f09.jpg)

**Comment by Aoi-hosizora** [comment]
Sorry, my server where my manhuagui service runs on maybe blocked by manhuagui official. I will migrate the service to another server later.

**Comment by AimerEGOIST** [comment]
> 抱歉，我的 manhuagui 服务所在的服务器可能被 manhuagui 官方屏蔽了。稍后我会将服务迁移到另一台服务器。

thanks bro🤣it's a sad story.

**Comment by Aoi-hosizora** [comment]
@AimerEGOIST This should be fixed now.
I have to setup a proxy on my old server, because I have no available server anymore :P
