### ISSUE TITLE
更新 1.2.0 版本后无法阅读

### ISSUE THREAD

**Issue by HiRA017** [Aoi-hosizora/manhuagui_flutter#20]
点击阅读任一漫画，均只会显示页数，并一直转圈载入中。

（不知是否为网络问题，境外（日本）直连如此、台湾、香港、北京节点全局代理问题依旧）

直接访问网站则没有任何问题。

**Comment by Aoi-hosizora** [comment]
这边测试了没有任何问题，你说的转圈是指 漫画章节阅读页面 还是 显示漫画信息和章节列表的页面。

转圈一段时间应该会显示错误信息的，看看显示错误是什么。

漫画和章节的信息是通过我个人的服务器获取再返回至客户端的，这边测试服务器网络没有问题。而所有图片和漫画章节页面是通过各自移动端的网络直接与漫画柜请求的，直接访问网站没有问题，理应漫画页面的获取也没有问题的。

**Comment by HiRA017** [comment]
是漫画阅读页面无限载入，且没有任何错误信息。

录制了视频，请参考：
[iCloud 视频分享](https://share.icloud.com/photos/0e7jBW5c_ZdPxKmvp3kDRtHYQ) 

> 设备：Google Pixel 5, Android 13 -  10月安全更新、未解锁 Bootloader、未 Root 或安装 Magisk Manager

> 网络环境：NTT 网络 - WiFi连接（Clash 全局代理 - 台湾节点）

**Comment by Aoi-hosizora** [comment]
麻烦你将预加载页数调整禁止预加载，然后看看其他章节的其他页是否会显示错误信息，并尝试一下长按保存页面看是否成功。

![image](https://user-images.githubusercontent.com/31433480/200608009-e9fd7252-d1e9-447c-946b-26754cf8082b.png)


另外，麻烦看一下漫画阅读页面的最后一页，是否是一直显示三个点或者图裂的图标。

![image](https://user-images.githubusercontent.com/31433480/200607949-d810ed34-d9f9-4b27-a53d-56bd0ab8f95c.png)

（上面两个图都是我在关闭网络后截下来的图）

**Comment by HiRA017** [comment]
谢谢您持续跟进！

禁用预加载后依然无限载入，且仍无任何错误提示；长按保存无效果、无保存成功/失败之提示，图库中也没有图片。

不过底页该位置的图片却可以正常显示
![Screenshot_20221109-012747](https://user-images.githubusercontent.com/91152901/200621714-8a49a920-a303-4caf-88ca-d06467b2b736.png)

我明天试试卸载重装。早点休息。

祝好(⁠.⁠ ⁠❛⁠ ⁠ᴗ⁠ ⁠❛⁠.⁠)

**Comment by Aoi-hosizora** [comment]
@HiRA017 你好，请问所述的 BUG 现在解决了吗

**Comment by HiRA017** [comment]
@Aoi-hosizora 谢谢你持续跟进。

没有，BUG 仍然存在。

现在暂时的解决方法就是在漫画详情页点击右上角，打开网页观看(⁠・⁠–⁠・⁠;⁠)⁠ゞ

**Comment by HiRA017** [comment]
1.2.1版本已修复此问题

Ver. 1.2.1 has patched this issue.
