### ISSUE TITLE
编译运行显示错误，系 统找不到指定的文件reloadable_photo_view.dart 

### ISSUE THREAD

**Issue by laotiezhu** [Aoi-hosizora/manhuagui_flutter#26]
请问这个代码必须运行在指定的flutter和dart版本上吗？编译不通过，显示下面的错误
lib/page/view/extended_gallery.dart:5:8: Error: Error when reading 'deps/photo_view/lib/reloadable_photo_view.dart': 系 统找不到指定的文件�?

import 'package:photo_view/reloadable_photo_view.dart' as reloadable_photo_view;
       ^
lib/page/view/extended_gallery.dart:163:101: Error: 'ReloadablePhotoViewState' isn't a type.
  late var _photoViewKeys = List.generate(widget.imageCount, (_) => GlobalKey<reloadable_photo_view.ReloadablePhotoViewState>());
                                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^
lib/page/view/extended_gallery.dart:191:96: Error: 'ReloadablePhotoViewState' isn't a type.
      _photoViewKeys = List.generate(widget.imageCount, (_) => GlobalKey<reloadable_photo_view.ReloadablePhotoViewState>());
                                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^
lib/page/view/extended_gallery.dart:262:36: Error: Method not found: 'ReloadablePhotoView'.
      child: reloadable_photo_view.ReloadablePhotoView(
                                   ^^^^^^^^^^^^^^^^^^^

**Comment by Aoi-hosizora** [comment]
很抱歉，没有及时回复你的问题。

解决方法：请你按照 README.md 里的 https://github.com/Aoi-hosizora/manhuagui_flutter#build-manually 步骤编译。

补充：Flutter 版本不一致的话是有可能回影响编译的，因为本项目的某些依赖库使用到了 Flutter 提供的一些很小众的接口，但是无法保证不同版本的 Flutter 采用项目兼容的接口，并且也可能会影响到界面的显示效果，因此最好采用相同的版本。

错误原因：本项目需要修改到几个第三方库，以实现一些细节上的展示功能。目前采用的方案是将这些库的源代码克隆到本项目根目录下的 `deps` 文件夹内，然后执行仓库提供的 `process_deps.sh` 脚本进行相应的修改，然后才可成功编译项目。
